eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8282

spring:
  cloud:
    gateway:
      routes:
      - id: hcb-accounts
        uri: lb://hcb-accounts
        predicates:
        - Path=/accounts/**
        filters:
        - RewritePath=/accounts/(?<path>), /$\{path}
      - id: frontend
        uri: http://localhost:3000
        predicates:
        - Path=/**
        filters:
        - RewritePath=/(?<path>), /$\{path}