eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

logging:
  level:
    org.springframework.cloud.netflix: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

server:
  port: 8282

spring:
  application:
    name: hcb-gateway
  cloud:
    gateway:
      routes:
      - id: hcb-accounts
        uri: lb://hcb-account-service
        predicates:
        - Path=/accounts/**
        filters:
        - StripPrefix=1
      - id: hcb-auth
        uri: lb://hcb-auth-service
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
      - id: frontend
        uri: http://localhost:3000
        predicates:
        - Path=/**
        filters:
        - RewritePath=/(?<path>), /$\{path}